hello/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home,name='home'),
    path('amaan',views.amaan,name='amaan'),
    path('david',views.david,name='david'),
    path('<str:name>',views.greet,name='greet'),
    
]

lec/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('hello/',include('hello.urls')),
    path('admin/', admin.site.urls),
    path('newyear/', include('newyear.urls')),
    path('tasks/', include('tasks.urls')),
    path('tasker/',include('tasker.urls')),
]

newyear/urls.py
from django.urls import path
from . import views

app_name = 'newyear'
urlpatterns = [
    path("",views.index,name='index')
]

tasker/urls.py
from django.urls import path
from . import views

app_name='tasker'
urlpatterns=[
    path('',views.tasks,name='tasks'),
    path('time',views.show,name='show'),
    path('<str:name>',views.greet,name='greet'),
]

tasks/urls.py
from django.urls import path
from . import views

app_name = 'tasks'
urlpatterns = [
    path("", views.index, name='index'),
    path("add",views.add, name='add')
]

hello/models.py
from django.db import models

# Create your models here.

newyear/models.py
from django.db import models

# Create your models here.

tasker/models.py
from django.db import models

# Create your models here.

tasks/models.py
from django.db import models

# Create your models here.

hello/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def home(request):
    return render(request,"hello/index.html")


def amaan(request):
    return HttpResponse("Hello, Amaan")

def david(request):
    return HttpResponse("Hello, David!")

def greet(request,name):
    # return HttpResponse(f"Hello, {name.capitalize()}!")
    
    return render(request,"hello/greet.html", {
        "name":name.capitalize()
        })

newyear/views.py
from django.shortcuts import render
import datetime
# Create your views here.
def index(request):
    now=datetime.datetime.now()
    return render(request,"newyear/index.html", {
        "newyear": now.month==1 and now.day==1
    })

tasker/views.py
from django.shortcuts import render
from django.http import HttpResponse
import datetime

# Create your views here.
def tasks(request):
    return render(request,'tasker/hi.html')

def greet(request,name):
    return render(request,'tasker/hi.html',{
        "name":name.capitalize()
    })

def show(request):
    now = datetime.datetime.now()
    return render(request,'tasker/time.html',{
        'time': now.strftime("%H:%M:%S %Y/%m/%d")
    })

tasks/views.py
from django import forms
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

tasks=["foo","bar","baz"]

class NewTaskForm(forms.Form):
    task=forms.CharField(label="Your New Task")
    # priority=forms.IntegerField(label="Priority",min_value=1,max_value=5)

# Create your views here.
def index(request):
    return render(request, 'tasks/index.html',{
        "tasks":tasks
    })

def add(request):
    if request.method == "POST":
        form= NewTaskForm(request.POST)
        if form.is_valid():
            task=form.cleaned_data["task"]
            tasks.append(task)
            return HttpResponseRedirect(reverse('tasks:index'))
        else:
            return render(request, 'tasks/add.html',{
                "form_variable":form
            })

    return render(request, 'tasks/add.html', {
        "form_variable":NewTaskForm()
    })

hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Greet variable</title>
</head>
<body>
    <h1>Hello, {{ name }}!</h1>
</body>
</html>

hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Greet</title>
</head>
<body>
    <h1>Hello, Home!</h1>
</body>
</html>

newyear/templates/newyear/index.html
{%load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Is is New Year?</title>
    <link href="{% static 'newyear/styles.css' %}" rel="stylesheet" type="text/css">
</head>
<body>
    {% if newyear %}
        <h1>Yes</h1>
    {% else %}
        <h1>No</h1>
    {% endif %}
</body>
</html>

tasker/templates/tasker/hi.html
{%extends 'tasker/layout.html'%}

{%block body%}
        <h6>Hi, {{name}}</h6>
        <a href="{%url 'tasker:show'%}">time</a>
{%endblock%}

tasker/templates/tasker/layout.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'tasker/styles.css'%}">
    <title>Show Date and Time</title>
</head>
<body>
    {%block body%}
    {%endblock%}
</body>
</html>

tasker/templates/tasker/time.html
{%extends 'tasker/hi.html'%}

{%block body%}
<h6>{{time}}</h6>
<a href="{%url 'tasker:tasks'%}amaan">back</a>
{%endblock%}

tasks/templates/tasks/add.html
{%extends "tasks/layout.html"%}

{%block body%}
    <h1>Add Tasks</h1>
    <form action="{% url 'tasks:add' %}" method="post">
        {% csrf_token %}
        {{ form_variable }}
        <input type="submit">
    </form>
    <a href="{%url 'tasks:index'%}">View Tasks</a>
{%endblock%}

tasks/templates/tasks/index.html
{%extends "tasks/layout.html"%}

{%block body%}
    <h1>Tasks</h1>
    <ul>
        {% for task in tasks %}
            <li> {{ task }} </li>
        {%endfor%}
    </ul>
    <a href="{%url 'tasks:add'%}">Add a New Task</a>
{%endblock%}

tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tasks</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>